/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket;

import java.awt.print.PrinterException;
import javax.swing.JOptionPane;

/**
 *
 * @author cordo
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        keluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        naker = new javax.swing.JTextField();
        napem = new javax.swing.JTextField();
        juru = new javax.swing.JTextField();
        harg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(110, 310, 80, 40);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(320, 220, 80, 40);

        jLabel1.setText("Total");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 250, 70, 30);
        getContentPane().add(tot);
        tot.setBounds(170, 250, 150, 30);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 330, 190);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(230, 310, 80, 40);

        jLabel2.setText("Nama Kereta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 100, 70, 30);

        jLabel3.setText("Nama Pembeli");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 130, 70, 30);
        getContentPane().add(naker);
        naker.setBounds(170, 100, 150, 30);
        getContentPane().add(napem);
        napem.setBounds(170, 130, 150, 30);
        getContentPane().add(juru);
        juru.setBounds(170, 160, 150, 30);
        getContentPane().add(harg);
        harg.setBounds(170, 190, 150, 30);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 70, 30);

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 190, 70, 30);

        jLabel6.setText("Jumlah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 220, 70, 30);
        getContentPane().add(jum);
        jum.setBounds(170, 220, 150, 30);

        jLabel7.setText("Aplikasi Tiket Kereta");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 20, 120, 50);

        setBounds(0, 0, 439, 613);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int penum = Integer.parseInt(jum.getText());
        int harga = Integer.parseInt(harg.getText());
        int hasil = penum+harga;
        tot.setText(String.valueOf(hasil));
        String kereta = naker.getText();
        String nama = napem.getText();
        String jurusan = juru.getText();
        String har = harg.getText();
        String jumla = jum.getText();
        String total = tot.getText();
        
        ta.append("		             PT.KAI\n"+
"                         STASIUN DRAGDRAGKAN\n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+

"--------------------------------------------------------------------------------------------------------------------- \n"+
"\n"+
"\n"+
"\n"+
"\n"+
" Nama Kereta    	: "+kereta+"\n"+
"\n"+
" Nama Penumpang	: "+nama+"\n"+
"\n"+
" Tujuan 		: "+jurusan+"\n"+
"\n"+
" Harga Tiket    	: Rp."+har+"\n"+
"\n"+
"\n"+
" Jumlah Penumpang	: "+jumla+"\n"+
"\n"+
"\n"+
" Total 		: Rp."+total+"\n"+
"\n"+
"\n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+
"\n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+
"                                                          ~TERIMAKASIH~");
        
        
        
        
        
        
        
    }//GEN-LAST:event_hitungActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try{
            boolean complete = ta.print();
            if(complete){
                JOptionPane.showMessageDialog(null,"Done Printing","Information",JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null,"Printing","Printer",JOptionPane.ERROR_MESSAGE);
            }
        }catch(PrinterException a){
            JOptionPane.showMessageDialog(null,print);
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harg;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jum;
    private javax.swing.JTextField juru;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField naker;
    private javax.swing.JTextField napem;
    private javax.swing.JButton print;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
